# -*- coding: utf-8 -*-
"""Amazon_review_anlaytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MRWGhRiaYTZVq_zL-zgLpFGH-7n9ROAF
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import glob

# Define the path to your CSV files
folder_path = '/content/drive/MyDrive/Reviewanalytics/*.csv'

# Load all CSV files into a list of DataFrames
file_list = glob.glob(folder_path)
dfs = [pd.read_csv(file) for file in file_list]

# Combine all DataFrames into one
data = pd.concat(dfs, ignore_index=True)

print(data.columns)

data.rename(columns={
    'reviews.text': 'Review_Text',
    'reviews.rating': 'Rating',
    'name': 'Product_Name',
    'reviews.date': 'Review_Date',
}, inplace=True)

# Drop rows with missing or empty reviews
data.dropna(subset=['Review_Text'], inplace=True)
data = data[data['Review_Text'].str.strip() != '']

# Remove duplicate reviews
data.drop_duplicates(subset=['Review_Text'], inplace=True)

# Add a dummy Customer_Name column if not present
if 'Customer_Name' not in data.columns:
    data['Customer_Name'] = ['Customer_' + str(i) for i in range(1, len(data)+1)]

# Convert Review_Date to datetime format
data['Review_Date'] = pd.to_datetime(data['Review_Date'], errors='coerce').dt.date

# Select relevant columns
cleaned_df = data[['Customer_Name', 'Review_Text', 'Product_Name', 'Review_Date', 'Rating']]

#print the final data
print(cleaned_df)

cleaned_df.to_csv('/content/drive/MyDrive/Reviewanalyticscleaned_customer_reviews.csv', index=False)