# -*- coding: utf-8 -*-
"""sentiment_analysis_transformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WWZupnp2wixy0ekg45d5vM3qAZKEq9Jc
"""

!pip install simple-salesforce transformers torch pandas

from simple_salesforce import Salesforce
import pandas as pd

sf = Salesforce(
    username='sakshinahar84128@agentforce.com',
    password='Msak23@man',
    security_token='xeG8rfapyXfNimNAIQwNejJO',
    domain='login'  # or 'test' if sandbox
)

batch_size = 500
total_updated = 0

while True:
    # ✅ Step 3: Query a batch of records from `amazon_reviews` with no sentiment label
    query = f"""
    SELECT Id, Review_text__c
    FROM amazon_reviews__c
    WHERE Sentiment_label__c = null
    LIMIT {batch_size}
    """

    results = sf.query_all(query)['records']

    if not results:
        print("✅ All records processed.")
        break

    df = pd.DataFrame(results).drop(columns='attributes')

    # ✅ Step 4: Run sentiment analysis
    df['Sentiment'] = df['Review_text__c'].apply(
        lambda x: classifier(x[:512])[0]['label'].capitalize() if pd.notnull(x) else 'Neutral'
    )

    # ✅ Step 5: Update records in Salesforce
    for _, row in df.iterrows():
        try:
            sf.amazon_reviews__c.update(row['Id'], {
                'Sentiment_label__c': row['Sentiment']
            })
        except Exception as e:
            print(f"⚠️ Failed to update Id {row['Id']}: {e}")

    total_updated += len(df)
    print(f"✅ Updated {total_updated} records so far...")

    time.sleep(1)